### PR TITLE
WIP: More reliable dark mode detection for macOS 10.15

### PR DESCRIPTION
**Pull request by weisJ**

### CODE REVIEW

**Comment by weisJ** [comment]
Due to [this](https://github.com/weisJ/auto-dark-mode/issues/3) it may be a bit more complicated.
However if the issue really is due to IntelliJ manually setting `NSApplication.appearance` it isn't an issue for darklaf at all.
@vlsi Could you check if the `isDarkModeEnabled` function works for your (independend of catalina auto mode).

**Comment by vlsi** [comment]
Just in case, the following in MacOSPreferenceMonitor always prints false in 10.14:

```
    private void onNotification() {
        boolean newDark = MacOSDarkMode.isDarkThemeEnabled();
        System.out.println("newDark = " + newDark);
```

**Comment by vlsi** [comment]
For unknown reasons,

```
NSLog(@"appearanceName: %@", [NSApplication sharedApplication].effectiveAppearance.name);
```

always produces `appearanceName: NSAppearanceNameAqua`

**Comment by vlsi** [comment]
This seems to be relevant: https://bugreports.qt.io/browse/QTBUG-83111

**Comment by weisJ** [comment]
There is a high chance that java itself manually specified `NSApplication.appearance` in this case `effectiveAppearance` returns the set value instead of the system appearance. Could you check if it has a non nil value? If yes it might be worth a try to set `[[NSApplication sharedApplication] setApearance:nil]` before checking the effective apperance.

**Comment by vlsi** [comment]
`[[NSApplication sharedApplication] setAppearance:nil];` does not help

**Comment by weisJ** [comment]
> This seems to be relevant: https://bugreports.qt.io/browse/QTBUG-83111

Does adding the linker(? could also be compiler. The fix for the issue mentions the linier, but I could only find the option for the compiler) flag `sdkRoot.map { ”-isysroot $it” }` help?

**Comment by weisJ** [comment]
It looks like the key problem is that the resulting library doesn’t have `LC_VERSION_MIN_MACOSX` specified. This can be checked using `otool -l <library>`.

**Comment by weisJ** [comment]
It seems like even a binary with the correct SDK version doesn’t solve the problem. There is a more general issue with the defaults of `net.java.openjdk.cmd` not specifying `NSRequiresAquaSystemAppearance`. Because the JDK itself not being build to support features of `10.14` AppKit inneres a value of `True` for the property. Specifically setting it to `false` resolves the issue but also forces all other java programs to use a dark title bar in dark mode (something the user shouldn’t be forced upon).

The propers solution is for apps using darklaf that want so support correct dark mode detection to  create a `<program>.app` distribution which specifies the appropriate key value pair.

**Comment by weisJ** [comment]
The app doesn't actually need to specify the key if enabling monitoring is the first thing the application does before interacting with any swing related classes. This way something like this is possible:

1. Patch the bundle of the running app by setting `NSRequiresAquaSystemAppearance` to `false`.
2. Interact with swing e.g. using `SwingUtilities.invokeLater(() -> {});`.
   - This loads the native libraries and because `NSRequiresAquaSystemAppearance` is `false` is linked against a version of `AppKit` that actually returns the correct value for `effectiveAppearance`.
3. Revert the changes made to the bundles `NSRequiresAquaSystemAppearance` setting.
   - Even if the program runs directly from the jar (i.e. if using OpenJDK it runs under `net.java.openjdk.cmd`) any other program started using java won't have their titlebars affected.
   - The titlebars of the current program are still affected.

**Comment by weisJ** [comment]
Closing due to #173.

**Pull request closed without merging**
